# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6634e8102ad47ff881e67d839a4dc3772290c4117b48775cb0dc7842fc39cb44e8f5c0d28daca08f12546e3f203c8e37c0824efac19925004e8a7e676e8a6bcc

test:
  secret_key_base: a37ec1e07983f221cca3f6e9ab2080f9754b65f40b3aea7382b88e85562556df5658664b85418322607f6a5dbd6ef748128c2aaf0073753652518fdf31e5cfdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
